#!/bin/bash

#print all numbers from 1 to 1000, skipping every third number

num=1
counter=1

until [ $num -gt 1000 ]; do
	if [ $counter -eq	3 ]; then
		counter=1
		num=$((num + 1))
	fi

	echo $num
	num=$((num + 1))
	counter=$((counter + 1))
done

